### ISSUE TITLE
Moq: Auto suggestion does not seem to work

### ISSUE THREAD

**Issue by Tdue21** [Litee/AgentZorge#3]
Hello, 
I have installed 0.7 on R# 2016.1.2 and VS 2015 Update 2. I am writing my unit tests using NUnit and Moq, and Agent Zorge seems like the right fit for this.
However, none of the feature described seems to be working with Moq.

**Comment by Tdue21** [comment]
Ok, not entirely true. The follow items seem to be working: 
- Moq: Suggest variable names based on the name of mocked interface
- Moq: Highlight callbacks with invalid number of arguments or incompatible argument types

The others (which really is the ones I want ;-) ) do not seem to be working.

**Comment by Litee** [comment]
Hey,
Let me double-check. Are you using Community or paid edition?

**Comment by Tdue21** [comment]
Sorry, it's the Professional Edition and R# is Ultimate

**Comment by Litee** [comment]
Thanks, will take a look

**Comment by Litee** [comment]
I have tried to reproduce with same version of R# and VS (I have Community edition though) and Moq v4.5.10, but plugin seems to work normally on my machine. :( Let me ask one question to rule out one possible (although unlikely) cause. When testing the plugin - do you have Moq referenced in "using" section? Without such reference plugin won't detect Moq library and will not suggest anything.

If my unlikely suggestion doesn't help then could you build very small VS project in which plugin is not working and send it to me. If it you would make screenshots of dropdowns without items that plugin is expected to bring - it will help even more.

**Comment by ltrzesniewski** [comment]
I have the same issue, and I can reproduce it with a brand new project. I can't get the `It.IsAny<string>` suggestion to appear:

![image](https://user-images.githubusercontent.com/7913492/32542372-a9d04c6e-c472-11e7-8423-949c6d63c415.png)

I simply created a new solution in VS 2017 15.4.2 / R# 2017.2.1 with a class library project, and added the latest version of NUnit (3.8.1) and Moq (4.7.145).

I don't think you'd benefit much if I upload that, but here it is anyway: [MoqTest.zip](https://github.com/Litee/AgentZorge/files/1453348/MoqTest.zip)

Maybe it has something to do with the error message on the `Setup` call itself:

![image](https://user-images.githubusercontent.com/7913492/32542537-2f5772ae-c473-11e7-9463-4b4d5e9f31fa.png)

**Comment by Litee** [comment]
I will take a look. I can see It.IsAny<string>(), but it is now at the end of the list - should be first:

![image](https://user-images.githubusercontent.com/400234/32570580-91fa762e-c4d5-11e7-9a10-f798d4f67fbb.png)

**Comment by ltrzesniewski** [comment]
It's strange... I can't find it in the list _at all_. Not at the beginning, not at the end, not near the `I` letter items. It's just not there. If I type `it` it narrows down the list but the suggestion is still not there.

The suggestion for `Callback` doesn't seem to be there either:

![image](https://user-images.githubusercontent.com/7913492/32651518-9b130546-c601-11e7-86a2-96f8aa291102.png)

Also look at the height of my scroll bar compared to the one on your screenshot: I have _much_ more items. I also have more filters at the bottom. I don't think we're using the same R# version here, are we?

**Comment by Litee** [comment]
I am using R# 2017.2.2 and VS Enterprise 15.4.3. Do you use Ctrl-Shift-Space to open the dropdown?

**Comment by ltrzesniewski** [comment]
Awwww... I didn't realize you needed to use Ctrl+Shift+Space to trigger AgentZorge suggestions.

I was simply using Ctrl+Space, I can confirm it works well with Ctrl+Shift+Space (with the caveat that the suggestion is at the bottom of the list).

As far as I can see this is not documented in the readme, or have I missed something?

**Comment by Litee** [comment]
:) My bad. I don't even remember why I assigned some helpers to basic auto-complete and some to smart ones. I just have published v0.8.2 where all helpers also support basic auto-complete.
