### ISSUE TITLE
Resharper 2017.2 support?

### ISSUE THREAD

**Issue by hermestobias** [Litee/AgentZorge#5]
This extension seems to be exactly what we need!

Any plans to add support for latest Resharper?

**Comment by Litee** [comment]
Hi! I will try. No hard guarantees because Resharper often does undocumented breaking changes, which makes upgrades very hard. Cross your fingers for me :)

**Comment by hermestobias** [comment]
Great! Good luck!

**Comment by Litee** [comment]
Published new version for 2017.2. Seems to be working for me.

**Comment by hermestobias** [comment]
Awsome work! Will give it a try tomorrow!

**Comment by hermestobias** [comment]
Doesn't seem to work for me unfortunately, the only refactoring I get is the naming of mock objects.

I am using Moq 4.7.99.0 through NuGet if that matters.

**Comment by Litee** [comment]
What is your VS version?

**Comment by hermestobias** [comment]
2017 pro

**Comment by Litee** [comment]
That's weird - I am using 2017 Pro as well with AgentZorge 0.8.0 and it works for me - e.g. suggestion of mock fields:

![image](https://user-images.githubusercontent.com/400234/32348246-383de266-c024-11e7-8c63-62d52038069a.png)

Maybe you could build a basic project that does not work for you, provide detailed steps + screenshot of  broken auto-completion and send those to me?

**Comment by hermestobias** [comment]
Hi, sorry for the delay! After upgrading to latest release it actually works, but not until I start typing part of the suggestion, and then still with some quirks. 

Example 1: Initial list of suggestions show "myMockThing" at top, and then all other keywords and Types in scope just as resharper usually does. When I type "m", then "myMockThing.Object" appears (on second place, still after "myMockThing").

Example 2: "It.IsAny<MyType>()" only appears after I have typed "It.", and then it shows after resharpers own list of members in It class. Additionally, if I select AgentZorges suggestion I get "It." twice, ie "It.It.IsAny<MyType>()".

**Comment by hermestobias** [comment]
And "new Mock<MyClass>().Object" suggestion is still not showing at all...

**Comment by Litee** [comment]
new Mock().Object is shown only if there are no other visible candidates. I will check other problems - they seem to happen in basic completion mode only.

**Comment by Litee** [comment]
I have looked through the code and it looks that basic completion simply has no "expected type", so plugin cannot find good candidates. I could investigate an alternative way to get this "expected type", but not sure it worth it when smart completion works nice and has proper semantics.

**Comment by hermestobias** [comment]
I see, haven't used smart completion (ctrl+**alt**+space) before, but when trying it everything works as advertised!

I consider this issue resolved then! Thanks for your support!
