### ISSUE TITLE
Parameterless callback should always be valid

### ISSUE THREAD

**Issue by ltrzesniewski** [Litee/AgentZorge#6]
A call to `ICallback.Callback(Action)` is always accepted by Moq, even if the function being set up takes parameters. It's handy when you don't need the argument values in your callback.

Here's an example of a valid call being reported as invalid:

![example](https://user-images.githubusercontent.com/7913492/32540781-032f6308-c46e-11e7-913e-c3ecedb5e1c2.png)

By the way, the `Returns` method doesn't seem to be checked like `Callback` is (there is no error highlight in the example below):

![image](https://user-images.githubusercontent.com/7913492/32540983-9f9e8a02-c46e-11e7-931c-8932c15663e6.png)

**Comment by Litee** [comment]
Lucas, thanks, I will take a look.

**Comment by Litee** [comment]
Fixed in v0.8.1

**Comment by ltrzesniewski** [comment]
Wow, that was fast, thanks! :)
